# Generated by Django 3.0.6 on 2020-06-03 01:42

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(storage=videos.models.VideoSystemStorage(), upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('duration', models.TimeField(editable=False)),
                ('probe_hash', models.CharField(editable=False, max_length=100, unique=True)),
                ('thumbnail_path', models.FilePathField(editable=False)),
            ],
        ),
    ]
