# Generated by Django 3.0.6 on 2020-06-03 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        ('users', '0002_history_recommended_savedvideos_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='vid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.Video'),
        ),
    ]
